name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # global variable to ensure all actions use Node.js 24

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest # Use the Playwright Docker image for a consistent testing environment
    container: mcr.microsoft.com/playwright:v1.58.2-jammy # Use a specific Playwright version for stability

    steps:
    - uses: actions/checkout@v4 # Checkout the repository to the GitHub Actions runner
    #- uses: actions/setup-node@v4
    #  with:
    #    node-version: lts/*

    - name: Install dependencies
      run: npm ci # Use npm ci for faster and more reliable installs in CI environments

    - name: Install Playwright Browsers
      #run: npx playwright install --with-deps
      run: npx playwright install chromium # Install only Chromium to save time and resources, adjust as needed for other browsers

    - name: Run Playwright tests
      run: npx playwright test # Use the list reporter for better readability in CI logs
      if: always() # Ensure that the tests run even if previous steps fail
    
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master # Generate Allure report from test results, ensuring it runs regardless of test outcomes
      if: always()
      with:
        allure_results: allure-results # Directory where Playwright test results are stored, adjust if different
        allure_history: allure-history # Directory to store historical test results for trend analysis, adjust if different
        keep_reports: 20 # Limit the number of reports to keep to manage storage, adjust as needed

    - name: Deploy Allure Report to GitHub Pages      
      if: always()
      uses: peaceiris/actions-gh-pages@v3 # Deploy the generated Allure report to GitHub Pages for easy access and sharing
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token for authentication, ensuring secure deployment
        publish_dir: ./allure-history # Directory containing the generated Allure report, adjust if different

    - uses: actions/upload-artifact@v4 # Upload the Playwright report as an artifact for later retrieval, ensuring it only uploads if the workflow was not cancelled
      if: ${{ !cancelled() }} # Ensure that the artifact is only uploaded if the workflow was not cancelled, preventing unnecessary uploads
      with:
        name: playwright-report # Name of the artifact for easy identification in the GitHub Actions UI
        path: playwright-report/ # Path to the Playwright report directory, adjust if different
        retention-days: 30 # Set the retention period for the uploaded artifact to 30 days
        